// config.bin - 08:44:37 01/21/18, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

#include "CfgEventHandlers.hpp"
#include "CfgPatches.hpp"
class CBA_Extended_EventHandlers;	// External class reference
#include "CfgVehicles.hpp"
#include "cfgWeapons.hpp"
