deadly_concertina_wire_fnc_pickup = compile preprocessFileLineNumbers "Deadly_Concertina_Wire\functions\fnc_pickup.sqf";
deadly_concertina_wire_fnc_place = compile preprocessFileLineNumbers "Deadly_Concertina_Wire\functions\fnc_place.sqf";
