// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class Deadly_CamouflageNet {
		name = "Deadly Camouflage Net";
		author = "Deadly";
		units[] = {"Deadly_Net_Digi_0","Deadly_Net_Digi_1","Deadly_Net_Hex_0","Deadly_Net_Hex_1","Deadly_Camouflage_Digi_0","Deadly_Camouflage_Digi_1","Deadly_Camouflage_Hex_0","Deadly_Camouflage_Hex_1"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"ace_interaction"};
	};
};
