// Generated by unRap v1.06 by Kegetys

class cfgVehicles {
	class Weapon_Bag_Base;	// External class reference
	
	class B_UAV_01_backpack_F : Weapon_Bag_Base {
		class assembleinfo;	// External class reference
		class EventHandlers;	// External class reference
	};
	
	class Deadly_Net_Digi_0 : B_UAV_01_backpack_F {
		_generalmacro = "Deadly_Net_Digi_0";
		author = "Deadly";
		displayname = "Camouflage Net (Woodland)";
		faction = BLU_F;
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_compact_digi_co.paa"};
		mapsize = 0.6;
		mass = 80;
		maximumload = 0;
		model = "\A3\weapons_f\Ammoboxes\bags\Backpack_Compact";
		picture = "\A3\weapons_f\ammoboxes\bags\data\ui\icon_B_C_Compact_dgtl_ca.paa";
		scope = 2;
		side = 3;
		
		class assembleInfo : assembleinfo {
			assembleto = "Deadly_Camouflage_Digi_0";
			base = "";
			displayname = Camouflage Net;
		};
	};
	
	class Deadly_Net_Digi_1 : Deadly_Net_Digi_0 {
		_generalmacro = "Deadly_Net_Digi_1";
		author = "Deadly";
		displayname = "Camouflage Vehicle Cover (Woodland)";
		faction = BLU_F;
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_gorod_oli_co.paa"};
		mapsize = 0.6;
		mass = 100;
		maximumload = 0;
		model = "\A3\weapons_f\Ammoboxes\bags\Backpack_Gorod";
		picture = "\A3\Weapons_F_beta\ammoboxes\bags\data\ui\icon_B_Gorod_oli_ca.paa";
		scope = 2;
		side = 3;
		
		class assembleInfo : assembleinfo {
			assembleto = "Deadly_Camouflage_Digi_1";
			base = "";
			displayname = Camouflage Vehicle Cover;
		};
	};
	
	class Deadly_Net_Hex_0 : Deadly_Net_Digi_0 {
		_generalmacro = "Deadly_Net_Hex_0";
		author = "Deadly";
		displayname = "Camouflage Net (Desert)";
		faction = BLU_F;
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_compact_ocamo_co.paa"};
		mapsize = 0.6;
		mass = 80;
		maximumload = 0;
		model = "\A3\weapons_f\Ammoboxes\bags\Backpack_Compact";
		picture = "\A3\Weapons_F\Ammoboxes\Bags\data\UI\icon_B_AssaultPack_ocamo_ca.paa";
		scope = 2;
		side = 3;
		
		class assembleInfo : assembleinfo {
			assembleto = "Deadly_Camouflage_Hex_0";
			base = "";
			displayname = Camouflage Net;
		};
	};
	
	class Deadly_Net_Hex_1 : Deadly_Net_Digi_1 {
		_generalmacro = "Deadly_Net_Hex_1";
		author = "Deadly";
		displayname = "Camouflage Vehicle Cover (Desert)";
		faction = BLU_F;
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_gorod_hex_co.paa"};
		mapsize = 0.6;
		mass = 100;
		maximumload = 0;
		model = "\A3\weapons_f\Ammoboxes\bags\Backpack_Gorod";
		picture = "\A3\Weapons_F\Ammoboxes\Bags\data\UI\icon_B_C_Gorod_hex_ca.paa";
		scope = 2;
		side = 3;
		
		class assembleInfo : assembleinfo {
			assembleto = "Deadly_Camouflage_Hex_1";
			base = "";
			displayname = Camouflage Vehicle Cover;
		};
	};
	/*
	class CamoNet_INDP_open_F;
	class CamoNet_INDP_big_F;
	class CamoNet_OPFOR_open_F;
	class CamoNet_OPFOR_big_F;
	*/
	
	class ThingX;
	class Deadly_Camouflage_Digi_0 : ThingX {
		ace_dragging_canCarry = 1;
		ace_dragging_carryDirection = 0;
		ace_dragging_carryPosition[] = {0,6,1.5};
		_generalMacro = "Deadly_Camouflage_Digi_0";
		accuracy = 0.1;
		animated = 1;
		armor = 200;
		cost = 1000;
		destrType = "DestructTent";
		displayName = "";
		editorCategory = "EdCat_Structures_Altis";
		editorPreview = "\A3\EditorPreviews_F\Data\CfgVehicles\CamoNet_INDP_open_F.jpg";
		editorSubcategory = "EdSubcat_Military";
		faction = "BLU_F";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsMaterials[] = {"\A3\Structures_F\Mil\Shelters\Data\CamoNet_BLUFOR.rvmat"};
		hiddenSelectionsTextures[] = {"\A3\Structures_F\Mil\Shelters\Data\CamoNet_INDP_CA.paa"};
		icon = "\A3\Structures_F\Mil\Shelters\Data\UI\map_CamoNet_CA.paa";
		ladders[] = {};
		mapSize = 14.46;
		model = "\A3\Structures_F\Mil\Shelters\CamoNet_open_F.p3d";
		nameSound = "obj_building";
		picture = "pictureStaticObject";
		scope = 2;
		scopeCurator = 0;
		simulation = "house";
		vehicleClass = "Structures_Military";
		
		class assembleInfo {
			assembleto = "";
			base = "";
			displayname = "Camouflage Net";
			dissasembleto[] = {"Deadly_Net_Digi_0"};
			primary = true;
		};
	};
	
	class Deadly_Camouflage_Digi_1 : Deadly_Camouflage_Digi_0 {
		ace_dragging_carryPosition[] = {0,6,2};
		_generalMacro = "Deadly_Camouflage_Digi_1";
		editorPreview = "\A3\EditorPreviews_F\Data\CfgVehicles\CamoNet_INDP_open_F.jpg";
		icon = "\A3\Structures_F\Mil\Shelters\Data\UI\map_CamoNet_Big_CA.paa";
		mapSize = 19.32;
		model = "\A3\Structures_F\Mil\Shelters\CamoNet_Big_F.p3d";
		
		class assembleInfo {
			assembleto = "";
			base = "";
			displayname = "Camouflage Vehicle Cover";
			dissasembleto[] = {"Deadly_Net_Digi_1"};
			primary = true;
		};
	};
	
	class Deadly_Camouflage_Hex_0 : Deadly_Camouflage_Digi_0 {
		_generalMacro = "Deadly_Camouflage_Hex_0";
		hiddenSelectionsTextures[] = {"\A3\Structures_F\Mil\Shelters\Data\CamoNet_OPFOR_CA.paa"};
		
		class assembleInfo {
			assembleto = "";
			base = "";
			displayname = "Camouflage Net";
			dissasembleto[] = {"Deadly_Net_Hex_0"};
			primary = true;
		};
	};
	
	class Deadly_Camouflage_Hex_1 : Deadly_Camouflage_Digi_1 {
		_generalMacro = "Deadly_Camouflage_Hex_1";
		hiddenSelectionsTextures[] = {"\A3\Structures_F\Mil\Shelters\Data\CamoNet_OPFOR_CA.paa"};
		
		class assembleInfo {
			assembleto = "";
			base = "";
			displayname = "Camouflage Vehicle Cover";
			dissasembleto[] = {"Deadly_Net_Hex_1"};
			primary = true;
		};
	};
};