// config.bin - 08:55:41 05/22/17, generated in 0.04 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

class CBA_Extended_EventHandlers;	// External class reference
#include "CfgEventHandlers.hpp"
#include "CfgPatches.hpp"
#include "cfgVehicles.hpp"
#include "cfgWeapons.hpp"