// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class Deadly_artilleryUp {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"ace_mk6mortar", "rhsusf_c_heavyweapons", "rhsusf_c_statics", "rhs_c_heavyweapons","orbis_artillery_config"};
	};
};
